apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-valkey-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/valkey"
