apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
type: Opaque
stringData:
  GITHUB_TOKEN: "{{ .Values.githubToken }}"
  MONGODB_PASSWORD: "{{ .Values.mongodbPassword }}"
  PG_PASSWORD: "{{ .Values.pgPassword }}"
  MYSQL_PASSWORD: "{{ .Values.mysqlPassword }}"
  VALKEY_PASSWORD: "{{ .Values.valkeyPassword }}"
