version: '3.7'
services:
  valkey:
    image: valkey/valkey:8
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${VALKEY_PORT}:${VALKEY_PORT}"
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  demo_app_dataset:
    image: dbazhenov/demo_app_dataset:0.1.6
    depends_on:
      valkey:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - VALKEY_ADDR=valkey
      - VALKEY_PORT=6379
      - DATASET_LOAD_TYPE=csv # github or csv
      - GITHUB_ORG=percona
      - GITHUB_TOKEN=
      - DATASET_DEMO_CSV_PULLS="data/csv/pulls.csv" # https://github.com/dbazhenov/github-stat/raw/refs/heads/main/data/csv/pulls.csv.zip
      - DATASET_DEMO_CSV_REPOS="data/csv/repositories.csv" # https://github.com/dbazhenov/github-stat/raw/refs/heads/main/data/csv/repositories.csv.zip
      - DELAY_MINUTES=10
      - DEBUG=false

  demo_app_web:
    image: dbazhenov/demo_app_web:0.1.6
    depends_on:
      valkey:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - VALKEY_ADDR=valkey 
      - VALKEY_PORT=6379
      - CONTROL_PANEL_PORT=3000
    ports:
      - "3000:3000"

  demo_app_load:
    image: dbazhenov/demo_app_load:0.1.6
    depends_on:
      valkey:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - VALKEY_ADDR=valkey
      - VALKEY_PORT=6379
      - LOAD_MYSQL=true
      - LOAD_POSTGRES=true
      - LOAD_MONGODB=true

volumes:
  valkey_data:
