version: '3.7'
services:
  valkey:
    image: valkey/valkey:8
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${VALKEY_PORT}:${VALKEY_PORT}"
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  demo_app_dataset:
    image: dbazhenov/demo_app_dataset:0.1.4
    depends_on:
      valkey:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - VALKEY_ADDR=valkey

  demo_app_web:
    image: dbazhenov/demo_app_web:0.1.4
    depends_on:
      valkey:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - VALKEY_ADDR=valkey 
    ports:
      - "${CONTROL_PANEL_PORT}:${CONTROL_PANEL_PORT}"

  demo_app_load:
    image: dbazhenov/demo_app_load:0.1.4
    depends_on:
      valkey:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - VALKEY_ADDR=valkey

volumes:
  valkey_data:
  pmm-data:
