version: '3.7'
services:
  valkey:
    image: valkey/valkey:8
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${VALKEY_PORT}:${VALKEY_PORT}"
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres:
    image: "percona/percona-distribution-postgresql:16.2-multi"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      LANG: en_US.utf8
      PGDATA: /data/db
    volumes:
      - pgdata:/data/db
      - ./data/init/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "5432:5432"

  mongodb:
    image: "percona/percona-server-mongodb:7.0-multi"
    volumes:
      - mongodata:/data/db
      - ./data/init/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: databaseAdmin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: dataset
    ports:
      - "27017:27017"

  mysql:
    image: "percona/percona-server:8.3.0-1.1-multi"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./data/init/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dataset
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot-password"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "3306:3306"
    command: >
      --performance-schema --innodb_monitor_enable=all
      --slow_query_log --slow_query_log_file=/mysql/slowlogs/slow.log --long_query_time=0

  demo_app_dataset:
    image: dbazhenov/demo_app_dataset:0.1.0
    depends_on:
      valkey:
        condition: service_healthy
    env_file:
      - .env

  demo_app_web:
    image: dbazhenov/demo_app_web:0.1.0
    depends_on:
      valkey:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${CONTROL_PANEL_PORT}:${CONTROL_PANEL_PORT}"

  demo_app_load:
    image: dbazhenov/demo_app_load:0.1.0
    depends_on:
      valkey:
        condition: service_healthy
    env_file:
      - .env

volumes:
  mongodata:
  pgdata:
  mysqldata:
  valkey_data:
  pmm-data:
