apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secret
type: Opaque
stringData:
  GITHUB_TOKEN: ""
  VALKEY_PASSWORD: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
data:
  GITHUB_ORG: percona
  CONTROL_PANEL_PORT: "3001"
  VALKEY_ADDR: valkey-service
  VALKEY_PORT: "6379"
  VALKEY_DB: "0"
  LOAD_MYSQL: "true"
  LOAD_POSTGRES: "true"
  LOAD_MONGODB: "true"
  DATASET_LOAD_TYPE: "csv" # github_chunks, github_consistent or csv
  DATASET_DEMO_CSV_PULLS: "data/csv/pulls.csv" # https://github.com/dbazhenov/github-stat/raw/refs/heads/main/data/csv/pulls.csv.zip
  DATASET_DEMO_CSV_REPOS: "data/csv/repositories.csv" # https://github.com/dbazhenov/github-stat/raw/refs/heads/main/data/csv/repositories.csv.zip
  DELAY_MINUTES: "3"
  DEBUG: "true"