apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  CONTROL_PANEL_PORT: "{{ .Values.controlPanelService.targetPort }}"
  VALKEY_ADDR: "{{ .Values.valkeyAddr }}"
  VALKEY_PORT: "{{ .Values.valkeyPort }}"
  VALKEY_DB: "{{ .Values.valkeyDB }}"
  DEBUG: "{{ .Values.debug }}"
