apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-web-service
spec:
  selector:
    app: {{ .Values.name }}-web
  ports:
    - protocol: TCP
      port: {{ .Values.controlPanelService.port | int }}
      targetPort: {{ .Values.controlPanelService.targetPort | int }}
      {{- if eq .Values.controlPanelService.type "NodePort" }}
      nodePort: {{ .Values.controlPanelService.nodePort | int }}
      {{- end }}
  type: {{ .Values.controlPanelService.type }}
